In [1]:
#import libraries
import numpy as np
import cv2 
import os



In [2]:
def FaceRec_Function1(img):
    
 
    #loading the haarcascade_frontalface xml file
    face_cascade = cv2.CascadeClassifier(r'C:\Users\NEW\haarcascade_frontalface_alt.xml')

    #converting original image to grayscale for the training
    img_gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)                   
    
    #detect multiscale images
    faces_rect = face_cascade.detectMultiScale(img_gray,1.3,7)
    
    return faces_rect,img_gray


In [4]:
 #unit testing for Function1
    
img=cv2.imread(r'C:\FrProject\images\0\AnithaImg18.jpg')

faces_rect,img_gray=FaceRec_Function1(img)
    
while True:
 
    cv2.imshow('Gray Image',img_gray)
    if cv2.waitKey(1) == 13: #press Enter key
        break
    
cv2.destroyAllWindows()

In [6]:
#parse through the image directory and subfolders for training
def FaceRec_Function2(img_directory):

    faces = []
    faceid = []

    for path,subdirnames,filenames in os.walk(img_directory):
        
        #parse filename in subfolder
         for filename in filenames:
            
            #test the systems file
            if filename.startswith("."):
                print("Skipped the System files")
                print("Skipped File:",filename)
                continue
           
            #trying to get the subdirectory name
            img_dirid=os.path.basename(path)
            print("FaceId:",img_dirid)
            
            
            #join the path and filename together
            img_fullpath=os.path.join(path,filename)
            print("Filename Path:",img_fullpath)
         
            test_img=cv2.imread(img_fullpath)
            
            #file has no image
            if test_img is None:
                print("No image found:", img_fullpath)
                
            #calling Function1
            faces_rect,gray_img=FaceRec_Function1(test_img)
           
            #if there's no faces detected,ignore and continue
            if len(faces_rect) == 0:
                
                print("No faces detected:", img_fullpath)
                continue
            
            (x,y,w,h) = faces_rect[0]
            crop_img = gray_img[y:y+w,x:x+h]
            
            faces.append(crop_img)
            faceid.append(int(img_dirid))
            
    print("Function2 finished")
    return faces,faceid

In [5]:
#unit testing for Function2

FaceRec_Function2(r"C:\FrProject\images\0")

FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg1.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg10.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg11.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg12.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg13.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg14.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg15.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg16.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg17.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg18.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg19.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg2.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg20.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg21.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg22.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg2

([array([[142, 143, 146, ...,  96, 101, 100],
         [142, 141, 140, ...,  91, 101, 100],
         [139, 139, 140, ...,  88,  95,  96],
         ...,
         [ 14,  10,  12, ...,  24,  30,  49],
         [ 15,  12,  13, ...,  21,  28,  47],
         [ 14,  14,  14, ...,  20,  29,  45]], dtype=uint8),
  array([[139, 139, 140, ..., 101, 100, 102],
         [137, 138, 140, ...,  98,  98, 100],
         [136, 136, 136, ...,  95,  95,  97],
         ...,
         [ 12,  12,  12, ...,  29,  54,  67],
         [ 14,  14,  13, ...,  29,  61,  71],
         [ 18,  10,  10, ...,  39,  58,  71]], dtype=uint8),
  array([[138, 140, 142, ...,  96,  97,  98],
         [138, 138, 138, ...,  90,  96,  97],
         [136, 136, 135, ...,  89,  94,  96],
         ...,
         [ 13,  10,  17, ...,  21,  31,  51],
         [ 14,  11,  14, ...,  20,  30,  52],
         [ 13,  11,  13, ...,  21,  29,  54]], dtype=uint8),
  array([[138, 137, 140, ..., 101, 103, 108],
         [139, 136, 139, ..., 100, 103,

In [8]:
#Train the faces using LBPH algorithm
def FaceRec_Function3(faces,faceid):
    
    #declare LBPH algorithm
    FaceRecognizer=cv2.face.LBPHFaceRecognizer_create() 
    
     #train the algorithm
    FaceRecognizer.train(faces,np.array(faceid))
    
    return FaceRecognizer


In [6]:
Face_Rect,FaceId=FaceRec_Function2(r"C:\FrProject\images\0")
FaceRecognizer=FaceRec_Function3(Face_Rect,FaceId)

FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg1.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg10.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg11.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg12.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg13.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg14.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg15.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg16.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg17.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg18.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg19.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg2.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg20.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg21.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg22.jpg
FaceId: 0
Filename Path: C:\FrProject\images\0\AnithaImg2

NameError: name 'FaceRec_Function3' is not defined

In [7]:
#draw the rectanle on the detected face
def FaceRec_Function4(test_img,face):
    (x,y,w,h)=face
    #put the rectangle onto the test_img
    cv2.rectangle(test_img,(x,y),(x+w,y+h),(255,0,0),thickness=3)

In [8]:
#put the text on the face rectangle 
def FaceRec_Function5(test_img,text,x,y):
#recieve the image,text the starting position of the image
    cv2.putText(test_img,text,(x,y),cv2.FONT_HERSHEY_COMPLEX,0.5,(0,0,255),2)